---
- name: Installing the Image service
  yum: name=openstack-glance state=latest

- name: Configuring the Image service 
  command: openstack-config --set /etc/glance/glance-api.conf DEFAULT sql_connection mysql://glance:{{ glance_password }}@{{ ansible_hostname }}/glance

- name: Configuring the Image service 
  command: openstack-config --set /etc/glance/glance-registry.conf DEFAULT sql_connection mysql://glance:{{ glance_password }}@{{ ansible_hostname }}/glance

- name: Configuring the Image service Database
  shell: echo {{ mysql_password }}| openstack-db --init --service glance --password {{ glance_password }}

- name: Creating user for the Glance
  shell: source /root/openrc.sh;keystone user-create --name glance --pass {{ glance_password }}

- name: Adding the Glance to the Service Project
  shell: source /root/openrc.sh;keystone user-role-add --user glance --tenant service --role admin

- name: Configuring the Glance service to use the keystone Identity services 
  shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_uri http://{{ ansible_hostname }}:5000;openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_host {{ ansible_hostname }};openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_tenant_name service;openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_user glance;openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_password {{ glance_password }};openstack-config --set /etc/glance/glance-api.conf paste_deploy flavor keystone;

- name: Configuring the Glance service to use the keystone Identity services
  shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_uri http://{{ ansible_hostname }}:5000; openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_host {{ansible_hostname }};openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_tenant_name service; openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_user glance; openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_password {{ glance_password }}; openstack-config --set /etc/glance/glance-registry.conf paste_deploy flavor keystone

- name: Configuring the Glance service to use the keystone Identity services
  shell: cp /usr/share/glance/glance-api-dist-paste.ini /etc/glance/glance-api-paste.ini;cp /usr/share/glance/glance-registry-dist-paste.ini /etc/glance/glance-registry-paste.ini

- name: Configuring the Glance service to use the keystone Identity services
  local_action: shell echo -en "auth_host={{ ansible_hostname }}\nadmin_user=glance\nadmin_tenant_name=service\nadmin_password={{ glance_password }}" >> /etc/ansible/controller_setup/templates/input.txt

- name: Configuring the Glance service to use the keystone Identity services
  copy: src=/etc/ansible/controller_setup/templates/input.txt dest=/root/


- name: Configuring the Glance service to use the keystone Identity services
  local_action: shell yes | rm /etc/ansible/controller_setup/templates/input.txt
- name: Configuring the Glance service to use the keystone Identity services
  shell: sed -i '/filter:authtoken/r /root/input.txt' /etc/glance/glance-api-paste.ini;sed -i '/filter:authtoken/r /root/input.txt' /etc/glance/glance-registry-paste.ini

- name: Creating service for Keystone
  shell: source /root/openrc.sh;keystone service-create --name=glance --type=image --description="Glance Image Service"

- name: Creating the Endpoint for the keystone
  shell: source /root/openrc.sh;keystone endpoint-create --service-id=`keystone service-list | grep -w glance | awk '{print $2}'` --publicurl=http://{{ ansible_hostname }}:{{ glance_port }} --internalurl=http://{{ ansible_hostname }}:{{ glance_port }} --adminurl=http://{{ ansible_hostname }}:{{ glance_port }}

- name: Starting the Glance Services
  service: name={{ item }} state=started
  with_items:
       - openstack-glance-api
       - openstack-glance-registry

- name: Making the Enable across the Reboot
  command: chkconfig {{ item }} on 
  with_items:
       - openstack-glance-api
       - openstack-glance-registry
- name: cleaning
  command: rm /etc/ansible/controller_setup/templates/input.txt
